<?php

namespace Mbroersen\LaravelDatabaseMigrate\Service\Database\Migrations\Template;

class ChangeColumn extends AddColumn
{
    public function get()
    {
        return parent::get() . '->change()'; // TODO: Change the autogenerated stub
    }
}

